### ISSUE TITLE
Hard to find opacity button

### ISSUE THREAD

**Issue by patchett2002** [ascr-ecx/colormoves#3]
couldnt find opacity button and how to apply that is referenced in the documentation.
Maybe adding a picture in the documentation would help?
from documentation below:
“Opacity – There is now the ability to control opacity separately for each inserted colormap. This is an especially useful feature when dealing with multivariate data or when seeking to accentuate one area over another. The opacity button is in the lower right.”

**Comment by goungy** [comment]
Hi this is Jérôme.
Yes we did not find the opacity button although we went through the documentation ;-).

**Comment by figs512** [comment]
The opacity button is the bottom icon on the right.  It displays the opacity or the opacity with the histogram.  Try a few different clicks and you will see the options.  Then, if you hover over the top of the color scale segment within the histogram that you would like to adjust, you will get an icon with two horizontal bars.  This will slide that segment of the colormap, lowering the opacity to your desiered level.
![optime](https://user-images.githubusercontent.com/20410118/42537131-45c7e962-8451-11e8-86d8-6181879a2494.jpg)
The attached image shows an example.

**Comment by figs512** [comment]
One request that I often hear is the ability to see the data distribution on the histogram not as 0 to 100%, but as the actual data range.  This would enable one to set the pins that divide the color scales at specific numerical values in the data.  Would this be of value?  If so, how much - a little?  Would use often?

**Comment by figs512** [comment]
The second request I often hear - the ability to export the colormaps, import them into ParaView or Matplotlib ant then have control points only at the intersection of the color scale segments.  As it is one gets all of the control points which can be a bit overwhelming to try and manipulate.  They provide greater resolution within the color scales but make them difficult to adjust.  Again, looking for feedback.  Would this be helpful and if so, a little, a lot, or?
We are looking for feedback and appreciate your comments.

**Comment by goungy** [comment]
Hi Ethan,
Request #1: actual data range. Yes I agree this could help... but as we are importing pictures and not image with original data, I am not sure how an analyst can make the link between say "original pressure value" and "absolute color value on picture".
Maybe I didn't get your request #1 right.
Request #2: we are not big users of Paraview, as we use a custom application called LOVE, we are fine with current way of exporting data.

**Comment by goungy** [comment]
Hi Ethan,

BTW you may close this issue as you merged the "label" work.

**Comment by EthanS94** [comment]
Thanks @goungy
