### ISSUE TITLE
Labels for mouse hovers

### ISSUE THREAD

**Issue by patchett2002** [ascr-ecx/colormoves#4]
when mouse pointer is pointing at a button it could help having a label appears.  Naively I see that there are seven buttons on the front page.  These should be targeted first for the hover labels.
The disk should probably be "save"
The Square Rainbow should be "hide/show color pane"
The Gaussian Distibution should be "toggle between modes"
The Wand?
The 'U" ?
The left and right ear?

![screen shot 2018-06-20 at 2 44 38 pm](https://user-images.githubusercontent.com/1746769/41683692-936ea9c6-7498-11e8-870e-62386bde4652.png)
![screen shot 2018-06-20 at 2 44 31 pm](https://user-images.githubusercontent.com/1746769/41683698-96d84590-7498-11e8-9b80-966e573b2832.png)

**Comment by goungy** [comment]
Hi, this is Jérôme.
Not sure about what the labels should be, and I guess you know better than us.
You get the idea though.

**Comment by goungy** [comment]
Hi Ethan,
Exactly what we requested: this really does help a lot to comprehend the usage of colormoves during first experimentations.
For instance, other issue we opened with opacity button we could not find is solved thanks to the label appearing when mouse hovers over the opacity button.

**Comment by EthanS94** [comment]
@goungy The branch has been merged and added to the page https://sciviscolor.org/ColorMoves/. Please re-open this issue if you have problems with the labels.
